select * from db where fname = "michael";
serkjekpjoekfgowpekfpfpof
owdfknwodkfnodkfvnwepofknvweofkn
wdofvnwodkfnvweofvnoewfvnqeowfvnefkn
owefknowefknvqpoefvnoqepfoefnvoekfnf
efivnoefvnqeofnvoqewnvowekfnvowen
odwjfnvovnoefknvowekfvnoewfkvnoe
weofknvweofvknweofvnweofvnewfvokn
